version: '3.4'

networks:
    postgres_donateto:
        driver: bridge

services:
  postgres_donateto:
    image: postgres:10.0-alpine
    container_name: donateto_postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "donate"
      POSTGRES_PASSWORD: "donate"
      POSTGRES_DB: "donate"
    networks:
     - postgres_donateto

  webapi_donateto:
     image: webapi_donateto
     container_name: webapi_donateto
     build:
       context: .
       dockerfile: src/DonateTo.WebApi/Dockerfile
     ports:
       - "8080:80"
       - "8081:433"

  webapplication_donateto:
    image: webapplication_donateto
    container_name: webapplication_donateto
    build:
      context: .
      dockerfile: src/DonateTo.WebApplication/Dockerfile
    ports:
        - "8080:80"
        - "8081:433"

volumes:
  db_volume: